---
- name: Create configuration folder
  file:
    path: "{{ y2s_config_dir }}"
    state: directory
    mode: 0755

- name: Create configuration file
  template:
    src: config.yml.j2
    dest: "{{ y2s_config_dir }}/config.yml"
    mode: 0644

- name: Configure Cronjob
  ansible.builtin.cron:
    name: "ynab2splitwise"
    minute: "{{ y2s_cron_minute }}"
    hour: "{{ y2s_cron_minute }}"
    day: "{{ y2s_cron_day }}"
    month: "{{ y2s_cron_month }}"
    weekday: "{{ y2s_cron_weekday }}"
    job: "docker run --rm -v {{ y2s_config_dir }}/config.yml:/app/config.yml {{ y2s_image_repository }}:{{ y2s_image_tag }}"